version: '3.7'
services:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  mysql:
    image: mysql:8 # https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/8.0/Dockerfile
    container_name: test_mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: 123321
      MYSQL_ROOT_PASSWORD: 123321
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql # https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/8.0/Dockerfile#L67
      - ./docker/mysql/configs/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
    command:
      - "--default-authentication-plugin=mysql_native_password"

  nginx:
    image: nginx:alpine
    container_name: test_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    depends_on:
      - php
    links:
      - php

  php:
    build:
      args:
        user: lidalevlion
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: test_php
    volumes:
      - .:/var/www
      - ./docker/php/configs/php-ini-overrides.ini:/usr/local/etc/php/conf.d/php-ini-overrides.ini:ro
      - ./docker/php/configs/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/configs/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - mysql

volumes:
  mysql-data:
